const DEFAULT_LOCALE = 'de-DE'
const DEFAULT_SEED = ''
const DEFAULT_ERROR_CHANCE = 0
const MIN_SEED_VALUE = 0
const MAX_SEED_VALUE = 1000000

export { DEFAULT_LOCALE, DEFAULT_SEED, DEFAULT_ERROR_CHANCE, MIN_SEED_VALUE, MAX_SEED_VALUE }
